### ISSUE TITLE
발견된 이슈들

### ISSUE THREAD

**Issue by Nyso97** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-21#153]
- [x] HealPack을 먹었을 때도 데미지 받았을 때와 똑같은 이펙트가 나타납니다
- [x] PlayerGUI에 현재 레벨 표시도 필요할 것 같습니다
- [x] 현재 이름이 <임시>로 되어있는 아이템들이 있어서 이름을 바꿔줘야 합니다
- [x] 자동 체력 회복이 안되고 있습니다
- [x] Ransomware의 투사체의 material이 검은색으로 보입니다
- [x] Ransomware 투사체 중 tracking bolt의 경우 에셋을 하나 적용해야 될 것 같습니다. 아니면 그냥 빼도 되고요
- [x] 포탑의 조준 레이저가 포탑이 공격받을 때 같이 깜박입니다
- [x] 바이러스가 벽 주위에서 넉백당할시 벽 밖으로 나가는 버그가 있습니다
- [x] 일시정지시 damage indicator가 같이 보이는 현상
![스크린샷 2024-12-16 223352](https://github.com/user-attachments/assets/e0448d8d-8790-458f-bf7f-e78226e61eb6)

- [x] 경험치 보석의 material을 수정할 필요가 있습니다

**Comment by tpwls6630** [comment]
추가적으로 회피율에 따른 회피 로직이 없는 걸로 알고 있습니다

**Comment by tpwls6630** [comment]
포탑의 조준 레이저가 깜빡이는 이슈는 레이저 gameObject가 터렛의 자식 오브젝트가 아니면 해결됩니다.
