### ISSUE TITLE
바이러스들의 속도가 너무 빠른 것 같습니다.

### ISSUE THREAD

**Issue by tpwls6630** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-21#35]
플레이어가 도망갈 수가 없어요

플레이어 속도를 높이던 바이러스 속도를 낮추던 해야할 것 같습니다

**Comment by Nyso97** [comment]
저도 이건 계속 생각하고 있긴 했습니다. 전체적으로 다 낮춰야 될 것 같아요
