### ISSUE TITLE
파티클 시스템 사이즈 조절 문제

### ISSUE THREAD

**Issue by tpwls6630** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-21#49]
화염방사기, 메테오의 파티클 시스템의 사이즈 조절을 편하게 할 수 없습니다. 오브젝트의 스케일 조정은 파티클의 크기에 전혀 영향을 주지 못합니다.

**Comment by charliennnsdk** [comment]
1. 화염방사기는 FX_FlameThrower 오브젝트의 Animation-FlameOn의 해당 값이 "2"로 되어 있을 텐데, 이 값을 수정해 주시면 됩니다.
<img width="340" alt="image" src="https://github.com/user-attachments/assets/76b8cf34-d7eb-4f69-917b-14bfd407c336">

2. 코어덤프의 경우, 별도로 StartSize를 조절하는 스크립트가 없어, ParticleSystem의 Start Size 값을 조절해 주시면 됩니다.
<img width="406" alt="image" src="https://github.com/user-attachments/assets/f6c31330-e535-470b-829d-624aa4070fb9">

**Comment by charliennnsdk** [comment]
+ 화염방사기의 애니메이션 파라미터는 "Fire_b" 이며, 이 파라미터가 true 일 때만 발사됩니다.
코어덤프의 경우, "isGrounded_b" 이며, 이 파라미터가 true일 때 터지고 애니메이션이 종료됩니다.

**Comment by tpwls6630** [comment]
@charliennnsdk 혹시 화염방사기를 옆으로 넓게 쏠 수 있는 파라미터도 있나요?

**Comment by charliennnsdk** [comment]
@tpwls6630 현재 해당 피드백은 진행중입니다. 파라미터만으로 해결 가능할 것 같아서 일단 연쇄번개 만든 후에 오늘 내로 적용할 예정입니다. 적용 후에 알려드리겠습니다!
