### ISSUE TITLE
벽 충돌시 플레이어(또는 카메라) 떨림

### ISSUE THREAD

**Issue by Nyso97** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-21#56]
벽에 닿은 상태로 계속 벽쪽으로 움직이려고 하면 캐릭터가 덜덜 떨리는 것처럼 보이는 현상이 있습니다.
해결해보려고 했는데 은근 어렵더라고요;;
움직임에 FixedUpdate를 대신 쓰는 방법이 있었는데 이러면 오히려 벽에 안닿아있을 때는 프레임이 좀 끊겨 보였습니다.
벽들에 대해서 Wall이라는 Tag를 줘서 얘네랑 닿아있을 때에만 다른 Move를 적용해야 하나? 하는 생각도 듭니다.

**Comment by tpwls6630** [comment]
rigidbody를 사용하기 때문에 움직임을 rigidbody로 구현해야 한다는 글을 본 적이 있습니다. 관련해서 연구를 조금 해봐야 할 것 같습니다.
