### ISSUE TITLE
PacketStream 투사체 비활성화 버그

### ISSUE THREAD

**Issue by Nyso97** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-21#86]
패킷 스트림 투사체가 나오자마자 바로 비활성화가 되는 버그가 있습니다.

floor의 rigidbody를 없애면 다시 정상작동하는걸 확인했습니다.

**Comment by tpwls6630** [comment]
floor의 rigidbody를 없애고 드론 투사체의 구현을 변경하겠습니다
