### ISSUE TITLE
방패가 몬스터를 때리지 않는 버그

### ISSUE THREAD

**Issue by tpwls6630** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-21#89]
가끔가다 방패가 몬스터에게 데미지를 주지 않는 버그가 있습니다.
거의 1/100의 확률 정도로 일어나는 것 같습니다.

![image](https://github.com/user-attachments/assets/e329c04d-ce8b-4c72-b667-c503051b35c5)

**Comment by Nyso97** [comment]
저는 이게 재현이 안돼서 확인을 못하겠네요;;

**Comment by Nyso97** [comment]
저 이거 이유 알아낸 것 같습니다....
W_VaccineRing의 치명타 확률이 5%, 치명타 데미지가 0%로 설정돼있습니다.
그래서 5%로 확률로 데미지가 안들어가는 것 같습니다 ㅋㅋㅋㅋ

다른 무기들도 이렇게 설정돼있는 것들이 있는데 얘네들은 바이러스랑 닿으면 사라지다보니 티가 안났던 것 같습니다
