### ISSUE TITLE
아이템 선택으로 드론을 얻으면 드론이 적을 바라보지 않는 버그

### ISSUE THREAD

**Issue by tpwls6630** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-21#90]
playercontroller에서 기본 무기를 드론으로 설정하면 드론이 적을 정상적으로 바라보지만
아이템 선택창에서 드론을 선택해 얻으면 드론이 적을 바라보지 않는 버그

**Comment by Nyso97** [comment]
이거 진짜 모르겠네요
일단 기본 무기를 드론으로 해도 multiprojectile 올려서 새 드론 생기면 그 드론도 적을 안바라봅니다

**Comment by Nyso97** [comment]
알아낸 것 같습니다. P_Drone의 애니메이션에서 Drone의 Rotation을 조절하고 있었습니다.
이게 왜 중간에 Spawn된 드론한테만 적용이 되던 건지는 모르겠지만 아무튼 animation에서 wing들만 남기고 drone은 빼니까 정상 작동합니다.
